INSERT INTO TBContato ([NOME], [EMAIL], [TELEFONE], [EMPRESA], [CARGO]) 
VALUES( 'JUCA', 'JUCA@GMAIL.COM', '998035074', 'NDD', 'TESTER' );

SELECT * FROM TBContato

DELETE FROM TBContato

DBCC CHECKIDENT('[TBContato]', RESEED, 0)


INSERT INTO TBTarefa([TITULO], [PRIORIDADE], [DATACRIACAO], [DATACONCLUSAO], [PERCENTUAL]) 
VALUES( 'ESTUDAR', 1, '2021/06/21', '2021/06/28', 50 );

SELECT * FROM TBTarefa

DELETE FROM TBTarefa

DBCC CHECKIDENT('[TBTarefa]', RESEED, 0) 


INSERT INTO TBCompromisso(ASSUNTO, [LOCAL], [DATA_INICIO], [DATA_FINAL], [ID_CONTATO]) 
VALUES( 'ESTUDAR', 'GUARUJÁ', '2021/07/21 09:00', '2021/07/21 10:00', 1 );

SELECT * FROM TBCompromisso

SELECT COUNT(*)
    FROM TBCompromisso
    WHERE
    '2021/07/21 09:00' BETWEEN DATA_INICIO AND DATA_FINAL
    OR  
    '2021/07/21 10:00' BETWEEN DATA_INICIO AND DATA_FINAL


DELETE FROM TBCompromisso

DBCC CHECKIDENT('[TBCompromisso]', RESEED, 0) 